Allow bitbake server startup
Bitbake server depends on hostname tool and fails
to start if not present:

ERROR: The following required tools (as specified by HOSTTOOLS) appear to
be unavailable in PATH